; The original, in Intel syntax.
    MOV BX, AX 
    AND BX, 08000h 
    XOR AX, BX 
    XOR AL, BH 
    SHR BX, 1 
    XOR AX, BX 
    XOR AL, BH 
    SHR BX, 1 
    XOR AX, BX 
    XOR AL, BH 
    SHR BX, 1 
    XOR AX, BX 
    XOR AL, BH 
    SHR BX, 1 
    XOR AX, BX 
    XOR AL, BH 
    SHR BX, 1 
    XOR AX, BX 
    XOR AL, BH 
    SHR BX, 1 
    XOR AX, BX 
    XOR AL, BH 
    SHR BX, 1 
    XOR AX, BX 
    XOR AL, BH 
    XCHG BH, BL    
    ADD AX, BX 
